#!/usr/bin/env bash

echo "Setting up macOS Preferences..."

# Enabling full keyboard access for all controls
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Avoiding the creation of .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Setting screenshots location to ~/Desktop
defaults write com.apple.screencapture location -string "$HOME/Desktop"

# Setting screenshot format to PNG
defaults write com.apple.screencapture type -string "png"

# Enable right click
defaults write com.apple.AppleMultitouchMouse MouseButtonMode -string "TwoButton"

# Enable right click and tap to click
defaults write com.apple.AppleMultitouchTrackpad TrackpadRightClick -boolean YES
defaults write com.apple.AppleMultitouchTrackpad TrackpadClicking -boolean YES

# Turn off Dock bounce
defaults write com.apple.dock no-bouncing -bool TRUE

killall Finder

echo "Done!"
